//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject_HiTech.BLL
{
    using FinalProject_HiTech.DAL;
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.OrderLines = new HashSet<OrderLine>();
            this.Authors = new HashSet<Author>();
        }
    
        public int BookId { get; set; }
        public string ISBN { get; set; }
        public string Title { get; set; }
        public double UnitPrice { get; set; }
        public int QOH { get; set; }
        public int PublisherId { get; set; }
        public int CategoryId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Publisher Publisher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderLine> OrderLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Author> Authors { get; set; }

        public void AddBook(Book book)
        {
            BookDB.AddRecord(book);
        }
        public List<Book> GetBookList()
        {
            return BookDB.GetListRecords();
        }

        public Book SearchBook(int bookId)
        {
            return BookDB.SearchRecord(bookId);
        }

        public void DeleteBook(int bookId) => BookDB.DeleteRecord(bookId);
        public void UpdateBook(Book book) => BookDB.UpdateRecord(book);

        public bool IsBookIdUnique(int bookId) => BookDB.IsUniqueBookId(bookId);
    }
}
