//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject_HiTech.BLL
{
    using FinalProject_HiTech.DAL;
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int EmployeeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public int JobId { get; set; }
        public int StatusId { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public virtual UserAccount UserAccount { get; set; }

        public void AddEmployee(Employee emp)
        {
            EmployeeDB.AddRecord(emp);
        }
        public List<Employee> GetEmployeeList()
        {
            return EmployeeDB.GetListRecords();
        }

        public Employee SearchEmployee(int empId)
        {
            return EmployeeDB.SearchRecord(empId);
        }

        public void DeleteEmployee(int empId) => EmployeeDB.DeleteRecord(empId);
        public void UpdateEmployee(Employee emp) => EmployeeDB.UpdateRecord(emp);

        public bool IsEmployeeIdUnique(int empId) => EmployeeDB.IsUniqueEmpId(empId);

    }
}
